# Branch Protection Rules for Kairos Repository
# 
# This file documents the recommended branch protection rules to restrict
# access to bot workflows and maintain repository security.
#
# These rules should be applied via GitHub Settings > Branches > Branch protection rules
# or using the GitHub API/Settings app: https://github.com/apps/settings

repository:
  name: Kairos
  description: Blockchain Audit Bot - Advanced Security and Monitoring System
  
  # Branch protection rules
  branches:
    - name: main
      protection:
        # Require pull request reviews before merging
        required_pull_request_reviews:
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          # This ensures CODEOWNERS must approve changes to workflows
          dismissal_restrictions:
            users: []
            teams: []
        
        # Require status checks to pass before merging
        required_status_checks:
          strict: true
          contexts: []
        
        # Enforce restrictions for who can push
        enforce_admins: true
        
        # Restrict who can push to matching branches
        restrictions:
          users: ["Kushmanmb"]
          teams: []
          apps: []
        
        # Require linear history
        required_linear_history: false
        
        # Allow force pushes
        allow_force_pushes: false
        
        # Allow deletions
        allow_deletions: false
        
        # Require conversation resolution before merging
        required_conversation_resolution: true
        
        # Lock branch (prevent all but administrators from pushing)
        lock_branch: false
        
        # Require signed commits
        required_signatures: false

    # Additional protection for bot-specific branches if needed
    - name: 'bot/**'
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
          require_code_owner_reviews: true
        enforce_admins: true
        restrictions:
          users: ["Kushmanmb"]
          teams: []
